ministryofjustice/opg-sirius-user-management

main.go, web/template/layout/header.gotmpl
Spotted when testing the integration
=> Use the public Sirius URL for navigation

internal/server/list_users.go, internal/server/list_users_test.go, internal/server/server.go, internal/sirius/users.go, internal/sirius/users_test.go, web/template/layout/navigation.gotmpl, web/template/users.gotmpl
As an OPG System Admin
I need to view all users' details
So that I can ensure they’re accurate
=> VEGA-260: List and find users

internal/server/add_user.go, internal/server/add_user_test.go, internal/server/change_password.go, internal/server/change_password_test.go, internal/server/list_users.go, internal/server/list_users_test.go, internal/server/server.go, internal/server/server_test.go, internal/sirius/add_user.go, internal/sirius/add_user_test.go, web/template/add-user.gotmpl, web/template/change-password.gotmpl, web/template/edit-my-details.gotmpl, web/template/layout/error-summary.gotmpl, web/template/users.gotmpl
This differs from the prototype as error handling on a 2 page form will be weird to handle.
=> VEGA-262 Add user

internal/server/resend_confirmation.go, internal/server/resend_confirmation_test.go, internal/server/server.go, internal/sirius/resend_confirmation.go, internal/sirius/resend_confirmation_test.go, internal/sirius/user.go, web/template/edit-user.gotmpl, web/template/resend-confirmation.gotmpl
After https://github.com/ministryofjustice/opg-sirius/pull/3777 is merged this will work.
=> VEGA-263 Add resend confirmation action and page

.circleci/config.yml
Output test coverage results and upload to codecov to track coverage
=> VEGA-235: Track test coverage

package.json, prototype/package.json, prototype/yarn.lock, yarn.lock
To get past some security issues
=> Upgrade dependencies

prototype/app/assets/javascripts/application.js, prototype/package.json, prototype/yarn.lock
We can now use `initAll` to automatically initialise components
=> Upgrade to MOJ frontend 0.2.x

internal/sirius/add_team.go, internal/sirius/add_team_test.go
To pair with ministryofjustice/opg-sirius#4271
=> VEGA-640: Use V1 add team endpoint

internal/sirius/team.go, internal/sirius/team_test.go
Companion to  ministryofjustice/opg-sirius#4279 to use the new V1 API endpoint
=> VEGA-639: Switch `Team` API handler to v1

internal/sirius/search_users.go, internal/sirius/search_users_test.go
=> VEGA-697 Remove use of v0 search

.github/workflows/build.yml
Otherwise dependabot will still try to create tags
=> Fix typo in dependabot's username

package.json, yarn.lock
To fix a security vulnerability in `set-value`
=> Upgrade webpack-cli

docker/docker-compose.yml, internal/server/edit_user.go, internal/server/edit_user_test.go, internal/sirius/edit_user.go, internal/sirius/edit_user_test.go, web/template/edit-user.gotmpl
Make field editable and sent it to the API
For VEGA-1405 #minor
=> Allow users to edit email addresses

.github/workflows/build.yml, docker/sirius-user-management/Dockerfile
And set required default branch config for `anothrNick/github-tag-action`
#patch
=> Bump insecure versions of libraries

README.md, cypress/e2e/users.cy.js, internal/sirius/search_users.go, internal/sirius/search_users_test.go, web/template/users.gotmpl
Show users team in Admin user search
=> SW-6384  Show users team in Admin user search

.github/workflows/build.yml
Move the definition of those values to new job and depend on its output in other jobs
For SP-1505 #patch
=> Set Pact tag/branch/commit properly

.github/workflows/build.yml
We need to evaluate the variable #patch
=> Fix tag pushing

cypress/e2e/add_team_member.cy.js, cypress/e2e/add_user.cy.js, cypress/e2e/edit_my_details.cy.js, cypress/e2e/edit_team.cy.js, cypress/e2e/edit_user.cy.js, web/template/layout/success-banner.gotmpl
Rename classes in HTML and Cypress tests
Fixes VEGA-2859 #patch
=> Migrate moj-banner to moj-alert

cypress/e2e/add_feedback.cy.js, cypress/e2e/random_reviews.cy.js, internal/sirius/add_feedback.go, internal/sirius/add_feedback_test.go, internal/sirius/edit_random_review_settings.go, internal/sirius/edit_random_review_settings_test.go, internal/sirius/random_reviews.go, internal/sirius/random_reviews_test.go
https://opgtransform.atlassian.net/browse/SW-7248
=> Sirius API calls should be routed to /supervision-api, not /api (User-management)

.github/workflows/build.yml
=> Remove github_token argument from semver-tag
