- Dockerfile
- docker-compose.yml
- index.html
- mock-api/Dockerfile
- mock-api/main.go
To demonstrate our proof-of-concept apps work in context, I've added the base code for two requirements:
- They must be built into the docker container `app` (the Dockerfile can be rewritten however you like)
- They must interact with the mock API
The mock API is written in Go and only supports `POST /auth/change-password`. It roughly emulates how the real endpoint works.
> VEGA-209: Setup repo for proof-of-concept apps

- build_assets.sh
We're not allowed to use New Transport outside of the *.service.gov.uk domain. Until we move, we can just not load the fonts and the frontend will fallback to Arial.
> Don't use New Transport font

- internal/server/edit_my_details.go
- internal/server/edit_my_details_test.go
- internal/server/health_check.go
- internal/server/my_details.go
- internal/server/my_details_test.go
- internal/server/server.go
- internal/sirius/permissions.go
- internal/sirius/permissions_test.go
- web/template/my-details.gotmpl
Checks if a user has permission to change their phone number before giving them the option to do so.
A few things I want to tidy up:
- ~~Create a route-blocking middleware to cause 403s, rather than managing in-handler~~
- Roles are generally used for authorization, not permissions, so middleware is heavy-handed
- Standardise client mocks to better handle multiple requests (e.g. `permissions { count, err, data }` rather than `permissionsCount, permissionsErr, permissionsData` etc.)
- Standardise API error handling?
- Move template permissions to map? (`can { editPhoneNumber: true } `)
> Fix: Check permissions before giving access to change phone number

- .circleci/config.yml
They cost 5 credits per minute rather than the default 10 (medium), and we don't need the extra resource 💰
> Fix: Use small resources for CircleCI

- Procfile
- package.json
We currently do Heroku build-and-deploy in the `Procfile` command. This is technically the deploy step, and Heroku enforces a 60 second timeout for something to listen on the port.
By specifying `heroku-postbuild` step, we can install dependencies and generate assets in the build step and not be caught out by timeout.
> Move Heroku build stage to package.json

- prototype/yarn.lock
There's a vulnerability in object-path, a patch bump to browser-sync removes the dependency
> Upgrade browser-sync to fix vulnerability

- internal/server/edit_team.go
- internal/server/edit_team_test.go
- internal/sirius/has_permission_test.go
- web/template/team-edit.gotmpl
Editing a team's type requires the post/team permission. Without it, the input fields are now disabled and POSTing the data will have no effect.
> VEGA-267: Check permissions to edit a team's type

- internal/server/add_team_member.go
- internal/server/add_team_member_test.go
If the response to a user-adding request returns a validation error (e.g. 400 + error messages), the addTeamMember handler needs to pass it to the UI.
> VEGA-236: Handle validation errors when adding a user

- .circleci/config.yml
- cypress/integration/add_team.spec.js
- cypress/integration/edit_team.spec.js
- docker/docker-compose.ci.yml
- docker/docker-compose.cypress.yml
- docker/pact-stub/pact_stub.go
- internal/sirius/add_team_test.go
- internal/sirius/add_user_test.go
- internal/sirius/change_password_test.go
- internal/sirius/edit_my_details_test.go
- internal/sirius/edit_team_test.go
- internal/sirius/edit_user_test.go
- internal/sirius/resend_confirmation_test.go
- internal/sirius/team_test.go
- internal/sirius/team_types_test.go
- internal/sirius/teams_test.go
Verifying the "teams" interactions on Sirius is difficult so I've decided to split them out to a separate contract that we can still use for mocking, but won't get published.
> VEGA-289 Modify contracts to allow them to pass with Sirius

- internal/server/server.go
- internal/server/server_test.go
- internal/sirius/add_team.go
- internal/sirius/add_team_test.go
- internal/sirius/add_user_test.go
- internal/sirius/change_password_test.go
- internal/sirius/client_test.go
- internal/sirius/edit_my_details.go
- internal/sirius/edit_my_details_test.go
- internal/sirius/edit_team.go
- internal/sirius/edit_team_test.go
- internal/sirius/edit_user.go
- internal/sirius/edit_user_test.go
- internal/sirius/has_permission.go
- internal/sirius/has_permission_test.go
- internal/sirius/my_details_test.go
- internal/sirius/resend_confirmation_test.go
- internal/sirius/search_users.go
- internal/sirius/search_users_test.go
- internal/sirius/team.go
- internal/sirius/team_test.go
- internal/sirius/team_types.go
- internal/sirius/team_types_test.go
- internal/sirius/teams_test.go
- internal/sirius/user.go
- internal/sirius/user_test.go
- Moved the `StatusError` assertions to separate tests (and added missing ones)
- Removed the possibility of returned the error from decoding the JSON when a unexpected status code is returned (as it wouldn't provide much useful information vs. status code + method + path)
> VEGA-289 Clean up tests

- .circleci/config.yml
- web/template/add-user.gotmpl
- web/template/change-password.gotmpl
- web/template/layout/navigation.gotmpl
- web/template/my-details.gotmpl
- Checked with Uchenna and she is happy with the 'add user' page changes
- I left 'OPG User' and 'COP User' in the label values for the OPG/ COP radio as I thought it made more sense. 
- I think the 'change password' page matches the attached screenshot (from Vega-306)
> Vega 449 update user management content

- .circleci/config.yml
- docker/puppeteer/Dockerfile
The chromium package in alpine3.12 got bumped from 83 to 86, which seems to cause new behaviour around forcing SSL. Downgrading to alpine3.11 gives us chromium 81 which doesn't have this problem.
> VEGA-463 Use older alpine to use older chromium

- internal/server/server.go
We should be comparing the public URL (used in views), not the internal one (used for API requests)
> VEGA-496: Correct URL comparison

- main.go
An empty environment variable is a valid base URL also.
> VEGA-513: Remove default for SIRIUS_PUBLIC_URL

- internal/server/server.go
We only use trailing slashes in URLs which are followed by parameters (like `/teams/edit/(id)`)
> VEGA-516: Remove trailing slash from /teams/add

- cypress/integration/unlock_user.spec.js
- docker/puppeteer/pa11yci.json
- internal/server/server.go
- internal/server/unlock_user.go
- internal/server/unlock_user_test.go
- web/template/edit-user.gotmpl
- web/template/unlock-user.gotmpl
Adds a popup on the edit page of locked user accounts, inviting admins to unlock the account. After a confirmation page, the account status is set back to "active".
> VEGA-532: Allow system admins to unlock accounts

- .circleci/config.yml
This means the GitHub API knows where to add the status check after verifying the Pact
> VEGA-510: Use full SHA1 for consumer version

- cypress/integration/delete_team.spec.js
- docker/puppeteer/pa11yci.json
- internal/server/delete_team.go
- internal/server/delete_team_test.go
- internal/server/edit_team.go
- internal/server/edit_team_test.go
- internal/server/server.go
- internal/sirius/delete_team.go
- internal/sirius/delete_team_test.go
- internal/sirius/has_permission.go
- internal/sirius/has_permission_test.go
- prototype/app/views/teams/delete.html
- prototype/app/views/teams/edit.html
- web/template/team-delete.gotmpl
- web/template/team-edit.gotmpl
- web/template/team.gotmpl
Pretty much the same as deleting users, although I had to hide the button between the `v1-teams:delete` permission because managers also have access to this page.
I fixed the URLs for testing page accessibility, which identified one accessibility problem I fixed and [a known issue with the design system](https://design-system.service.gov.uk/components/radios/#known-issues) which I covered up.
NB: You can URL-hack to edit and delete an already-deleted team, which we should fix (by returning 410 when a team has been deleted).
> VEGA-401: Give sysadmin users the ability to delete team entities

- .github/codeql/codeql-config.yml
- .github/dependabot.yml
- .github/workflows/codeql-analysis.yml
- prototype/app/views/index.html
- prototype/yarn.lock
Now ignores the `./prototype` directory when checking Dependabot and CodeQL
Also bumps `browser-sync` to get past a couple of vulns
> Skip prototype into autochecking

- .dockerignore
- .github/codeql/codeql-config.yml
- .github/workflows/codeql-analysis.yml
- cypress/integration/edit_team.spec.js
- internal/sirius/edit_team.go
- internal/sirius/edit_team_test.go
- web/template/team-edit.gotmpl
Uses `PATCH /api/v1/teams/:id` rather than `PUT /api/team/:id`, which provides enhanced validation and testing (ministryofjustice/opg-sirius#4288).
Despite the endpoint being PATCH and accepting partial objects, we send the entire thing across every time because of how the `EditTeam` interface has already been designed. Teams are changed infrequently enough that this isn't really a concern.
I also stripped out some old references to the prototype directory.
> VEGA-641: Use v1 endpoint to update teams

- internal/sirius/roles.go
- internal/sirius/roles_test.go
Switches `roles` service to use the new v1 API added by [opg-sirius#4581](https://github.com/ministryofjustice/opg-sirius/pull/4581)
> VEGA-633: Use v1 Roles API

- internal/sirius/search_users.go
- internal/sirius/search_users_test.go
This ensures we send a valid HTTP request, and specifically fixes an [nginx bug](https://trac.nginx.org/nginx/ticket/196) which causes requests with ` H` in the query to immediately fails as 400.
> VEGA-745: Escape query string in API request

- .github/workflows/build.yml
GitHub actions creates a merge commit against the base branch, which is what `github.sha` refers to.
`github.event.pull_request.head.sha` instead refers to the last commit on the branch.
We want to use the last commit, because we eventually pass this back to the GitHub API to set status checks.
> Fix sha used for Jenkins tag

- .github/workflows/codeql-analysis.yml
When GitHub Actions runs on a pull request, it creates a merge commit with the latest changes from the source branch.
We used to run `checkout HEAD^2` to go _back_ and test the latest commit on the branch, but CodeQL now recommends against this and instead advises testing the merge commit.
This helps identify issues caused by two PRs created at the same time.
> Run CodeQL on merge commit

- .github/workflows/build.yml
In PRs, it should be `github.event.pull_request.head.sha`. In other builds it should just be `github.sha`.
> Set Pact tag depending on context

- go.mod
- go.sum
Go 1.14 is no longer supported as each major Go release is supported until there are two newer major release and Go is currently on 1.16. This PR is to upgrade the Go language version.
> SW-3481 upgrade language to 1.16

- .github/dependabot.yml
When dependabot submits security updates, we want it to use the `-` separator in PR branches so they can be validly tagged by ECR.
We can only specify this by adding configuration to `dependabot.yml`. In doing so we have to switch from security updates to *all* updates.
I've limited dependabot to production dependencies (i.e. not `devDependencies`) to reduce the noise, because we were previously overwhelmed by updates to build packages. We will however *still get security updates for dev dependencies*.
> Configure branch name for dependabot JS updates

- .github/workflows/main.yml
There are organisation-level keys available so that we don't need to manage our own. Use them instead of repo-specific keys.
> Use org keys for Veracode upload and scan

- .github/workflows/build.yml
`github.head_ref` is only set on pull request events, so we should handle push events differently. There isn't an alternative variable, but we can only push to the main branch so we know that will be the branch name.
Also push `--all-tags` to ensure both `latest` and the semver tag are pushed on main builds.
> Fix docker tagging

- .github/workflows/build.yml
We currently build the `app` and `pact-stub` containers in multiple workflow jobs. This is a big waste of compute and slows down the workflow time.
This change instead builds both containers at the start of the workflow, stores them in the Actions' cache, and then reuses them in later jobs.
I looked at doing the same for the `cypress` and `puppeteer` images but there's no speed benefit since they're only used in one job each anyway. If we really wanted to speed them up, we could store them in ECR and pull rather than build.
This takes about three minutes off the build time ([before](https://github.com/ministryofjustice/opg-sirius-user-management/actions/runs/895748537), [after](https://github.com/ministryofjustice/opg-sirius-user-management/actions/runs/896333669))
> Cache docker images in workflow

- .github/workflows/build.yml
Dependabot doesn't have access to GitHub Actions secrets, so cannot perform all of the steps of the current pipeline. Specifically, it cannot write to Pact broker or push to AWS.
This change alters the pipeline for dependabot PRs. Instead of writing to the broker, it pulls the latest copy of the contract and diffs against it. It passes if the local contract has not added or changed anything compared to latest (we allow it to remove things, since the remote has some extra data).
It skips pushing to AWS entirely, since there is generally no need for it. If a dependency upgrade requires deployment, we can cherry-pick the commit onto a dev-authored PR and run the original pipeline in full.
> Alter pipeline for dependabot PRs

- .github/workflows/build.yml
I renamed the previous step to `push`, so the variable reference needs to match
> Fix parameter name reference

- package.json
- yarn.lock
Major updates to webpack and copy-webpack-plugin get past security vulnerabilities in set-value, glob-parent and ssri
> Upgrade dependencies to fix security vulnerabilities

- .github/workflows/build.yml
`github.head_ref` is only set on pull requests, so fallback to `main` on other builds.
> Set PACT_TAG to branch name

- internal/server/list_teams.go
- web/template/teams.gotmpl
This was probably included as a copy-paste error, but it doesn't need to be passed into the request.
> Remove XSRF token from GET form

- internal/sirius/add_team_test.go
- internal/sirius/add_user_test.go
- internal/sirius/edit_team_test.go
- internal/sirius/random.go
To prevent "user/team already exists" errors, add randomisation to unique identifiers.
#patch
> Fix Pact tests by adding randomisation

- .github/workflows/build.yml
It won't be able to publish results, run scans, push files; so  skip those steps like we do for renovate.
#patch
> Don't expect Renovate to have permissions

- .github/workflows/build.yml
We can take off the guardrails, since Renovate is a properly authorised app with access to all the secrets it needs to do normal workflow jobs
> Fix renovate config

- .github/workflows/build.yml
Without being enabled, every version is treated as a real bump.
> Use prerelease mode for tags

- internal/server/delete_user.go
- internal/server/delete_user_test.go
- internal/server/edit_user.go
- internal/server/edit_user_test.go
- internal/sirius/add_user.go
- internal/sirius/add_user_test.go
- internal/sirius/delete_user.go
- internal/sirius/delete_user_test.go
- internal/sirius/edit_user.go
- internal/sirius/edit_user_test.go
- internal/sirius/user.go
- internal/sirius/user_test.go
- web/template/edit-user.gotmpl
Rather than using the `/auth/*` endpoints in the frontend container (which merge API+Membrane requests), use the API endpoints directly and ignore Membrane.
Fixes VEGA-1685 #patch
> Use API user endpoints

- internal/sirius/add_team.go
- internal/sirius/add_user.go
- internal/sirius/delete_team.go
- internal/sirius/delete_user.go
- internal/sirius/edit_my_details.go
- internal/sirius/edit_random_review_settings.go
- internal/sirius/edit_team.go
- internal/sirius/edit_user.go
- internal/sirius/my_details.go
- internal/sirius/my_permissions.go
- internal/sirius/random_reviews.go
- internal/sirius/roles.go
- internal/sirius/search_users.go
- internal/sirius/team.go
- internal/sirius/team_types.go
- internal/sirius/teams.go
- internal/sirius/user.go
We don't care about errors when closing the body of an API request
Fixes VEGA-1706 #patch
> Ignore gosec false positives

- internal/server/edit_user.go
- internal/server/edit_user_test.go
- web/template/edit-user.gotmpl
If the user has any hidden roles (i.e. in `user.roles` but not shown in `/api/v1/roles`), add them as hidden form items so that they're not lost when the user is edited.
Involved changing a few tests that already referred to hidden roles when they should have been using "real" ones.
For VEGA-1765 #patch
> Ensure user retains hidden roles when edited

- renovate.json
Turn off lockfile maintenance in Renovate: it only updates transient dependencies, which creates lots of noise and doesn't provide us with any benefit
> Disable lockfile maintenance

- cypress/plugins/index.js
- docker/cypress/Dockerfile
- package.json
- yarn.lock
1. path module was not recognised, so add a polyfill for it.
2. Axe was trying to load a file but webpack was insisting on a fullySpecified path, and Axe was not using one (change in behaviour from webpack 4 to 5).
cypress have fixed this behaviour for their own packages, but it has not been fixed for the cypress-axe plugin.
> VEGA-2145 Fix two issues preventing upgrade to cypress 13 #minor

- .github/workflows/build.yml
- package.json
- web/assets/load-classes.js
- web/assets/main.js
- web/assets/main.scss
- web/template/layout/page.gotmpl
- yarn.lock
- Update path references to include `/dist`
- Move body-class-setting into separate file (it needs to be done before we import govuk-frontend and we block inline scripts)
- Update icon paths
For VEGA-2202 #minor
> Upgrade govuk-frontend and moj-frontend

- internal/server/server.go
- internal/server/server_test.go
If the request is cancelled, issue a 499 response and return immediately. Don't render a template, as it will never be shown. Don't log the error, as we know what it is and have handled it.
#minor
> Handle cancelled requests
